import { useState } from "react";
import { motion } from "framer-motion";
import Head from "next/head";
import Section from "../components/Section";
import About from "../components/About";
import Navbar from "../components/Navbar";
import Cursor from "../components/Cursor";

export default function Home() {
  const [navlink, setNavlink] = useState<string>("home");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main
        initial={{
          scale: 0.1,
          opacity: 0.2,
        }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ duration: 0.8, ease: "circOut" }}
        style={{
          background: "black",
          height: "100vh",
          color: "white",
          alignItems: "center",
          justifyContent: "center",
          display: "flex",
          flexDirection: "column",
          backgroundImage: "url('/bg.webp')",
          backgroundSize: "cover",
        }}
      >
        {navlink === "home" && <About setNavlink={setNavlink} />}

        {navlink !== "home" && (
          <Navbar currentLink={navlink} setCurrentLink={setNavlink} />
        )}

        {navlink === "contact" && (
          <Section
            content="contact"
            navlink={navlink}
            setNavlink={setNavlink}
            id="contact"
          />
        )}

        {navlink === "work" && (
          <Section
            content="work"
            navlink={navlink}
            setNavlink={setNavlink}
            id="work"
          />
        )}

        {navlink === "skills" && (
          <Section
            content="skills"
            navlink={navlink}
            setNavlink={setNavlink}
            id="skills"
          />
        )}
      </motion.main>

      <Cursor />
    </>
  );
}
